# Site settings
title: 心路笔记
header-img: "images/gallery-example-3.jpg"
tagline: "心路笔记"  
description: "遙遠的地方 繁華中盡是空幽"
baseurl: ""
url: "http://bestbao.top"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Bao"
  email: baoyudu@outlook.com
  bio: "举目四望山依旧，回首却见人无常"

# Data
gavatar: img/favicon.jpg
favicon: img/favicon.ico



github_username: baoyudu  
#weibo_username: baoyudu0
#zhihu_username: baoyudu0

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Bao"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : bestbao
  disqus :
      short_name : bestbao

# Analytics and webmaster tools stuff goes here
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
prose:
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Input your title here"
          type: "text"

      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Input your abstract here"
          type: "text"

      - name: "category"
        field:
          element: "hidden"
          value: "blog"
